databases:
  # 1. O Banco de Dados PostgreSQL
  - name: motorotas-db
    plan: free

services:
  # 2. Nosso Serviço Web ÚNICO
  # Ele serve a API e roda os scripts de fundo como threads.
  - name: motorotas-app
    type: web
    plan: free
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn app:app --timeout 120"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: motorotas-db
          property: connectionString
      - key: IFOOD_CLIENT_ID
        sync: false
      - key: IFOOD_CLIENT_SECRET
        sync: false
