databases:
  # 1. O Banco de Dados PostgreSQL
  - name: motorotas-db
    plan: free

services:
  # 2. Nosso Serviço Web ÚNICO
  # Ele serve a API e roda os scripts de fundo como threads.
  - name: motorotas-app
    type: web
    plan: free
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn app:app --timeout 120"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: motorotas-db
          property: connectionString
      - key: IFOOD_CLIENT_ID
        sync: false
      - key: IFOOD_CLIENT_SECRET
        sync: false
```

### O Que Fazer Agora (Passo a Passo)

1.  **Limpeza:** Delete os arquivos `api.py`, `main.py`, e `process_routes.py` do seu projeto.
2.  **Criação:** Crie os novos arquivos `app.py`, `collector.py`, e `processor.py` e cole o conteúdo correspondente.
3.  **Atualização:** Substitua o conteúdo do seu `render.yaml` pelo novo código simplificado.
4.  **Commit e Push:** Envie todas essas alterações para a sua branch `api-test` no GitHub.
    ```bash
    git add .
    git commit -m "refactor: Unifica aplicação para deploy no Render"
    git push
    

